# version: '3.8'

services:
  app:
    depends_on:
      - db
    image: theilich/app:latest
    container_name: app
    hostname: app
    command: ./wait.sh db ./app_entrypoint.sh
    env_file:
      - ./.env
    ports:
      - "8080:8080"

  db:
    image: postgres:16.2-alpine3.19
    container_name: db
    hostname: db
    env_file:
      - ./.env
    ports:
      - "5000:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

