CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action_time" datetime NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0));
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "authusers_aboutus" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(10000) NOT NULL, "content" text NOT NULL, "whatwedo1" varchar(10000) NULL, "whatwedo2" varchar(10000) NULL, "whatwedo3" varchar(10000) NULL, "button_text" varchar(1000) NULL);
CREATE TABLE IF NOT EXISTS "authusers_announcements" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(10000) NOT NULL, "link" varchar(200) NULL);
CREATE TABLE IF NOT EXISTS "authusers_contact" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(1000) NOT NULL, "email" varchar(254) NOT NULL, "subject" varchar(1000) NOT NULL, "message" text NOT NULL, "date_added" datetime NULL);
CREATE TABLE IF NOT EXISTS "authusers_faqs" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "Question" varchar(10000) NOT NULL, "Answer" text NOT NULL);
CREATE TABLE IF NOT EXISTS "authusers_feedback" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(1000) NOT NULL, "email" varchar(254) NOT NULL, "subject" varchar(1000) NOT NULL, "message" text NULL, "date_added" datetime NULL);
CREATE TABLE IF NOT EXISTS "authusers_getintouch" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(10000) NULL, "address" varchar(10000) NULL, "email" varchar(254) NULL, "email2" varchar(254) NULL, "phone" integer NULL, "phone2" integer NULL);
CREATE TABLE IF NOT EXISTS "authusers_packageprice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "package_name" varchar(1000) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "package_info" varchar(1000) NOT NULL, "package_price" integer NOT NULL, "package_period" varchar(1000) NOT NULL, "package_details1" varchar(1000) NULL, "package_details2" varchar(1000) NULL, "package_details3" varchar(1000) NULL, "package_details4" varchar(1000) NULL, "package_details5" varchar(1000) NULL, "package_details6" varchar(1000) NULL, "package_details7" varchar(1000) NULL, "package_details8" varchar(1000) NULL, "package_details9" varchar(1000) NULL, "package_details10" varchar(1000) NULL);
CREATE TABLE IF NOT EXISTS "authusers_privacy_and_terms" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(10000) NOT NULL, "content" text NOT NULL, "link" varchar(200) NULL);
CREATE TABLE IF NOT EXISTS "authusers_review" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(1000) NOT NULL, "subject" varchar(1000) NOT NULL, "email" varchar(254) NOT NULL, "status" varchar(1000) NOT NULL, "review" text NOT NULL, "date_added" datetime NULL);
CREATE TABLE IF NOT EXISTS "authusers_support_and_customerservice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(10000) NOT NULL, "content" text NOT NULL, "link" varchar(200) NULL);
CREATE TABLE IF NOT EXISTS "authusers_profile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "first_name" varchar(1000) NULL, "last_name" varchar(1000) NULL, "email" varchar(254) NULL, "bio" varchar(1000) NULL, "aboutme" text NULL, "country" varchar(1000) NULL, "cover_photo" varchar(100) NOT NULL, "image" varchar(100) NOT NULL, "joined" datetime NULL, "creator" bool NOT NULL, "normal_user" bool NOT NULL, "facebook" varchar(10000) NULL, "dribble" varchar(10000) NULL, "twitter" varchar(10000) NULL, "instagram" varchar(10000) NULL, "behance" varchar(10000) NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "authusers_newsletter" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "email" varchar(254) NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "authusers_modelnotes" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(1000) NULL, "content" text NULL, "date_added" datetime NOT NULL, "usernote_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "authusers_newsletter_user_id_accf0550" ON "authusers_newsletter" ("user_id");
CREATE INDEX "authusers_modelnotes_usernote_id_68ca935f" ON "authusers_modelnotes" ("usernote_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "post_post_tags" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "post_id" char(32) NOT NULL REFERENCES "post_post" ("id") DEFERRABLE INITIALLY DEFERRED, "tag_id" integer NOT NULL REFERENCES "post_tag" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "post_post" ("id" char(32) NOT NULL PRIMARY KEY, "picture" varchar(100) NOT NULL, "caption" varchar(10000) NOT NULL, "posted" date NOT NULL, "likes" integer NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "post_post_tags_post_id_tag_id_15c628ee_uniq" ON "post_post_tags" ("post_id", "tag_id");
CREATE INDEX "post_post_tags_post_id_6adf1c1b" ON "post_post_tags" ("post_id");
CREATE INDEX "post_post_tags_tag_id_cb551e85" ON "post_post_tags" ("tag_id");
CREATE INDEX "post_post_user_id_b9c97aef" ON "post_post" ("user_id");
CREATE TABLE IF NOT EXISTS "post_follow" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "follower_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "following_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "post_follow_follower_id_30a4d4cf" ON "post_follow" ("follower_id");
CREATE INDEX "post_follow_following_id_1cb2c456" ON "post_follow" ("following_id");
CREATE TABLE IF NOT EXISTS "post_tag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "slug" varchar(50) NOT NULL UNIQUE, "title" varchar(75) NOT NULL);
CREATE TABLE IF NOT EXISTS "post_stream" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "following_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "post_id" char(32) NULL REFERENCES "post_post" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "date" datetime NOT NULL);
CREATE INDEX "post_stream_following_id_1fc48816" ON "post_stream" ("following_id");
CREATE INDEX "post_stream_post_id_207bb8c1" ON "post_stream" ("post_id");
CREATE INDEX "post_stream_user_id_330aec76" ON "post_stream" ("user_id");
CREATE TABLE IF NOT EXISTS "post_likes" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "post_id" char(32) NOT NULL REFERENCES "post_post" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "post_likes_post_id_b7e609e3" ON "post_likes" ("post_id");
CREATE INDEX "post_likes_user_id_12e60720" ON "post_likes" ("user_id");
CREATE TABLE IF NOT EXISTS "authy_profile_favourite" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "profile_id" integer NOT NULL REFERENCES "authy_profile" ("id") DEFERRABLE INITIALLY DEFERRED, "post_id" char(32) NOT NULL REFERENCES "post_post" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "authy_profile_favourite_profile_id_post_id_40a317a3_uniq" ON "authy_profile_favourite" ("profile_id", "post_id");
CREATE INDEX "authy_profile_favourite_profile_id_ce06f2d6" ON "authy_profile_favourite" ("profile_id");
CREATE INDEX "authy_profile_favourite_post_id_9353731c" ON "authy_profile_favourite" ("post_id");
CREATE TABLE IF NOT EXISTS "comment_comment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "body" text NOT NULL, "post_id" char(32) NOT NULL REFERENCES "post_post" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "date" datetime NULL);
CREATE INDEX "comment_comment_post_id_357153e3" ON "comment_comment" ("post_id");
CREATE INDEX "comment_comment_user_id_6078e57b" ON "comment_comment" ("user_id");
CREATE TABLE IF NOT EXISTS "directs_message" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" datetime NOT NULL, "is_read" bool NOT NULL, "sender_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "reciepient_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "body" text NULL);
CREATE INDEX "directs_message_sender_id_3a1c1c0b" ON "directs_message" ("sender_id");
CREATE INDEX "directs_message_user_id_2344c818" ON "directs_message" ("user_id");
CREATE INDEX "directs_message_reciepient_id_04aff480" ON "directs_message" ("reciepient_id");
CREATE TABLE IF NOT EXISTS "notification_notification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "notification_types" integer NULL, "text_preview" varchar(100) NOT NULL, "date" datetime NOT NULL, "is_seen" bool NOT NULL, "sender_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "post_id" char(32) NULL REFERENCES "post_post" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "notification_notification_sender_id_1f59f8e1" ON "notification_notification" ("sender_id");
CREATE INDEX "notification_notification_user_id_e9d6f5f4" ON "notification_notification" ("user_id");
CREATE INDEX "notification_notification_post_id_7eb3677e" ON "notification_notification" ("post_id");
CREATE TABLE IF NOT EXISTS "authy_profile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "bio" varchar(200) NULL, "first_name" varchar(200) NULL, "last_name" varchar(200) NULL, "location" varchar(200) NULL, "url" varchar(200) NULL, "image" varchar(100) NULL);
